openapi: 3.0.1
info:
  version: '1.0'
  title: Payment service
servers:
  - url: '/api/v1/payment-service'
tags:
  - name: Payment Management
    description: Operations with Payment entities
paths:
  /payment/{id}:
    post:
      tags:
        - Payment Management
      summary: Pay order
      description: Pay order by id
      operationId: pay
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        description: order
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDto'
  /payment/:
    get:
      tags:
        - Payment Management
      summary: Get all payments
      description: Get all payments
      operationId: getAllPayments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentDto'

components:
  parameters:
    id:
      name: id
      in: path
      description: Order ID
      required: true
      schema:
        type: string
      example: 599sdf49
  schemas:
    PaymentDto:
      type: object
      properties:
        id:
          description: Unique Identifier of Payment
          type: integer
          format: int32
          readOnly: true
        orderId:
          description: Order id.
          type: string
          readOnly: true
          maxLength: 100
        customerId:
          description: Id of User.
          type: string
          maxLength: 100
        total:
          description: Total of order.
          type: double
    PaymentType:
      type: string
      enum:
        - CASH
        - CARD
        - CARD_ONLINE
    Status:
      type: string
      enum:
        - OK
        - CANCEL
        - FAILED
    OrderDto:
      type: object
      properties:
        id:
          description: Unique Identifier of Order.
          type: string
          readOnly: true
        name:
          description: Name of Order.
          type: string
          maxLength: 100
        customerId:
          type: string
        total:
          type: number
          format: double
        shippingType:
          $ref: '#/components/schemas/ShippingType'
        status:
          $ref: '#/components/schemas/OrderStatus'
        products:
          type: object
          additionalProperties:
            type: integer
        paymentId:
          type: integer
      required:
        - name
        - customerId
        - total
        - shippingType
        - status
        - products
    ShippingType:
      type: string
    OrderStatus:
      type: string